# Site settings
title: AJ Stuyvenberg
email: astuyve@gmail.com
description: Software Engineer, Parachute Enthusiast.
url: "https://aaronstuyvenberg.com"
google_analytics: 'UA-121620651-1'

author:
  name: Aaron Stuyvenberg
  twitter_username: astuyve
  github_username: astuyve

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Misc settings
featured-image-source:

# Social settings
github_url: https://github.com/astuyve
instagram_url: https://instagram.com/aj.stuyv
linkedin_url: https://www.linkedin.com/in/aaron-stuyvenberg
twitter_url: https://twitter.com/astuyve
youtube_url: https://www.youtube.com/channel/UCsWwWCit5Y_dqRxEFizYulw

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
kramdown:
  syntax_highlighter:  rouge
  input:               GFM # Github Flavored Markdown
  hard_wrap:           false # do not replace newlines by <br>s

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
