# Site settings
title: AJ Stuyvenberg
email: astuyve@gmail.com
description: The internet home of Aaron (AJ) Stuyvenberg. Software Engineering blog, BASE Jumping videos, misc ramblings.
url: "https://aaronstuyvenberg.com"

author:
  name: Aaron Stuyvenberg
  twitter_username: astuyve
  github_username: astuyve

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 15

# Misc settings
featured-image-source:

# Social settings
github_url: https://github.com/astuyve
instagram_url: https://www.instagram.com/aj.stuyv
linkedin_url: https://www.linkedin.com/in/aaron-stuyvenberg
twitter_url: https://twitter.com/astuyve
mastodon_url: https://hachyderm.io/@ajs
youtube_url: https://www.youtube.com/channel/UCsWwWCit5Y_dqRxEFizYulw

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
kramdown:
  syntax_highlighter: rouge
  input: GFM # Github Flavored Markdown
  hard_wrap: false # do not replace newlines by <br>s
sass:
  style: compressed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
